### ISSUE TITLE
自动收集路由路径跳转

### ISSUE THREAD

**Issue by scripted-C20** [sunpm/unisave#26]

**Comment by sunpm** [comment]
有没有调用的方法示例，比如想怎样调用路由方法跳转

**Comment by scripted-C20** [comment]
你这是在为难我胖虎，跟文件里一样调用函数名就ok了

**Comment by sunpm** [comment]
打个比方，有个**个人中心**页面，假设路由是`pages/me/index`，你是想`goMePage()`跳转到该页面，，多个页面使用 `goMePage()`方法，这个时候 `pages/me/index` 要改成 `pages/my-page/index`，这种情况应该如何解决呢？是将所有`goMePage()` 重构为`goMyPage()`，还是将`goMyPage`函数内部路径改为`pages/my-page/index`

**Comment by scripted-C20** [comment]
这种情况应该是重新生成，假设能监听到，那么你说的两种情况都要改变成你说的结果

**Comment by sunpm** [comment]
那岂不是改变一个路由文件的位置，所有.vue 文件的内容都要检索，查看有没有这个方法，有就去重构。这样牵一发而动全身的插件，如果改漏了或者改错了，可以开发者都不知道错在哪

**Comment by scripted-C20** [comment]
那是开发者的事情，最简单的还是重新生成，让开发者自己去更改调用函数，利用编辑器一键替换

**Comment by sunpm** [comment]
不太明白，重新生成什么，有没有代码示例

**Comment by scripted-C20** [comment]
soory说错了 是自动收集，如你说的假设需求，有个已有的文件名要更改，那么建议此时自动收集更改后的名称，生成一个新的跳转函数

**Comment by sunpm** [comment]
太自动化意味着可拓展性越局限，失去了模板的意义。可以另外开发 vite 插件，而不是将它纳入模板中。

**Comment by scripted-C20** [comment]
说的好！这个vite插件任务就交给你了，思路都发给你了，到时候我点10下star

**Comment by scripted-C20** [comment]
当然你也可以设置成开关，可以作为模板亮点

**Comment by sunpm** [comment]
明年找我领插件

**Comment by scripted-C20** [comment]
批评

**Comment by scripted-C20** [comment]
我关了 省的你逼逼赖赖
